# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    - cargo build --release

  doc:
    - RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --target-dir .
    - rm -rf release
    - rm -rf debug